version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py3pylint

jobs:
  test-py3pylint:
    docker:
      - image: circleci/python:3.6-jessie
    environment:
      - TOX_ENV: py3pylint
    working_directory: ~/pystrigo
    steps:
      - checkout
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install tox
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make testone TOX_ENV=$TOX_ENV
      - save_cache:
          paths:
            - .tox
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

